version: 0.2
phases:
  install:
	commands:
  	- sudo nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
  	- timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  build:
	commands:
  	- docker images
  	- touch ajay
  	- docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-weekly zap-baseline.py -t http://petstore-demo-endpoint.execute-api.com/petstore/pets
      -g gen.conf -r testreport.html
  	- docker images
  	- docker ps -a
  	- docker exec -it ajay54 /bin/bash
  	- ls

  post_build:
	commands:
  	- pwd
  	- ls
